### PR TITLE
Added provisional search language to the user guide for review.

### PR DESCRIPTION
**Pull request by annamgibson**
Added provisional search language to the user guide for review.

### CODE REVIEW

**Comment by annamgibson** [comment]
@csbailey5t  Help! Did I break something!? I don't know what I did here, but all checks appear to have failed. All I did was add language to the user guide about how to search.

**Comment by csbailey5t** [comment]
@annamgibson this looks fine, and it's running locally for me. I just got netlify to re-run the build to see if it was just downtown due to internal errors on their end. We'll see if that addresses it. We can always merge anyway since it is working locally.

**Comment by annamgibson** [comment]
Thanks, @csbailey5t . I'm not able to view the deploy preview, and I was going to ask Adam to review the content before committing, so I'm going to run it by him via email before we go ahead. I don't know why it's telling me that the checks and deploy preview have failed, but I'm relieved that I haven't screwed something up!

**Comment by csbailey5t** [comment]
@annamgibson you can find a deploy preview here: https://ddnp-2tmh8gmrf-ddnp.vercel.app/usage/guide#searching-the-ddnp

**Review by annamgibson — COMMENTED** [review]
Edited search language

**Pull request merged**
